{% set name = "FreeClimber" %}
{% set version = "0.3.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: "https://github.com/adamspierer/FreeClimber.git"
  git_tag: dev

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - ffmpeg-python >=0.2.0
    - matplotlib >=3.1.3
    - numpy >=1.18.1
    - pandas >=1.0.0
    - pip >=20.0.2
    - python >=3.4 
    - scipy >=1.4.1
    - trackpy >=0.4.2
    - wxPython >=4.0.4
    
  run:
    - ffmpeg-python >=0.2.0
    - matplotlib >=3.1.3
    - numpy >=1.18.1
    - pandas >=1.0.0
    - python >=3.4
    - scipy >=1.4.1
    - trackpy >=0.4.2
    - wxPython >=4.0.4

test:
  imports:
    
about:
  home: "https://github.com/adamspierer/FreeClimber.git"
  license: "MIT"
  license_family: "OTHER"
  license_file: "LICENSE.txt"
  summary: "Background subtracting particle detector that quantifies vertical velocity of particles using a local linear regression"
  doc_url: "https://github.com/adamspierer/FreeClimber/blob/master/TUTORIAL.md"
  dev_url: "https://github.com/adamspierer/"

extra:
  recipe-maintainers:
    - "adamspierer"
